### ISSUE TITLE
Tests not pulling in testPipeline

### ISSUE THREAD

**Issue by benmcosker** [kenzanlabs/pipeline-test-karma#4]
https://github.com/kenzanlabs/pipeline-test-karma

Pipeline currently not functioning:
https://github.com/kenzanlabs/pipeline-test-karma/tree/feature/KEY-19-test-karma

Pipeline needs to be updated to new pipeline-test-node, pipeline-validatejs, & pipeline-handyman.  Support for require needs to be included so that internal unit tests are run.

 Currently two PR's on this:
https://github.com/kenzanlabs/pipeline-test-karma/pull/1
https://github.com/kenzanlabs/pipeline-test-karma/pull/3

this is the work I have thus far:
https://github.com/benmcosker/pipeline-test-karma/pull/3

cc: @obuckley-kenzan | @jpoo90

**Comment by obuckley-kenzan** [comment]
@benmcosker 
> Pipeline currently not functioning:

In what way?  What's the expected vs actual?  Please provide a clear overview of the problem.

**Comment by benmcosker** [comment]
When trying an ```npm install`` from this devDependency:
```    "pipeline-test-karma": "0.1.0-SNAPSHOT",```

comes back with this error:
```
npm ERR! registry error parsing json
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/bmcosker/.nvm/versions/node/v5.1.0/bin/node" "/Users/bmcosker/.nvm/versions/node/v5.1.0/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.9.0

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /pipeline-test-karma not found in group repository &quot;NPM&quot; [id=npm].</title>
```

**Comment by obuckley-kenzan** [comment]
@benmcosker 
Where are you getting that tag / version from?  This pipeline has not been published to NPM because there is no code in master so not sure if you are trying to use this or trying to complete work on this pipeline, or what.

It looks like there are PR's open but they were blocked due to build failures.  Let me curate those first but I'm not seeing this as an issue with the pipeline per se, since it's not even published / listed here
https://github.com/kenzanlabs/keystone#active-projects

**Comment by obuckley-kenzan** [comment]
going to close this, seems to be some confusion here.  we can reopen if needed but I think this issue is making assumptions that a pipeline is available when it's actually not.
